### ISSUE TITLE
Explain what P S L Pa I F T are

### ISSUE THREAD

**Issue by cheater** [YoshifumiFuyuno/Search-from-Popup-or-ContextMenu#34] opened 2022-02-03 20:07 UTC
in Options, under "Search engines", there are multiple check boxes, and it is not clear what they do exactly. There should be an explanation at the very top. There is an explanation when you hover each check box, but that's not immediately obvious, so users will not find it.

**Comment by YoshifumiFuyuno** [comment] 2022-02-04 11:47
Duplicate of #30

**Closed by YoshifumiFuyuno** 2022-02-04 11:47 UTC
