### ISSUE TITLE
Set popup default option to "never" to prevent freezes.

### ISSUE THREAD

**Issue by cheater** [YoshifumiFuyuno/Search-from-Popup-or-ContextMenu#19] opened 2022-02-03 19:08 UTC
Please set popup default to "never" to prevent UI freezes, like in #18

**Comment by YoshifumiFuyuno** [comment] 2022-02-04 10:36
Duplicate of #18

**Closed by YoshifumiFuyuno** 2022-02-04 10:36 UTC

**Comment by cheater** [comment] 2022-02-04 15:45
In my mind those are two separate things. In #18 the idea is to solve the freezes at all, but to actually solve them. In #19 the idea is to not create the popup code in the first place to avoid the freezes, while not solving the real issue. If #19 is implemented, the freezes will still happen for someone who turns on the popup. If #18 is implemented, #19 becomes obsolete, but #18 might be much more difficult.
