### ISSUE TITLE
Cleanly unload popup javascript when it's no longer needed

### ISSUE THREAD

**Issue by cheater** [YoshifumiFuyuno/Search-from-Popup-or-ContextMenu#20] opened 2022-02-03 19:15 UTC
It seems that once the addon loads the javascript, even when the popup option is set to "never", that javascript is never unloaded.

Related issues: #18 #19

**Comment by YoshifumiFuyuno** [comment] 2022-02-04 10:37
Duplicate of #18

**Closed by YoshifumiFuyuno** 2022-02-04 10:37 UTC
